pipeline {
    agent any
    
    tools {
        maven "maven_tool"
        jdk "jdk8"
        
        /*
        Link para agregar credenciales de Oracle, al configurar un JDK para descargar
        Enter Oracle Credentials
        http://<hostname>/descriptorByName/hudson.tools.JDKInstaller/enterCredential
        */
    }
    
    stages {
        stage("Checkout") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://gitlab.com/codilabs/Ear-Test.git']]])
            }
        }
        
        stage("Scan & Build") {
            environment {
                scannerHome = tool "sonar_scanner"
            }
            steps {
                parallel "Scan": {
                    withSonarQubeEnv("sonarqube_server") {
                        bat """
                        "${scannerHome}/bin/sonar-scanner" \
                        -Dsonar.projectKey=earTest \
                        -Dsonar.projectName=Act-4-EarTest \
                        -Dsonar.projectVersion=0.1 \
                        -Dsonar.sources=testWAR/src \
                        """
                        //-Dsonar.java.binaries=./target/
                    }
                    timeout(time: 10, unit: "MINUTES") {
                        waitForQualityGate abortPipeline: true
                    }
                }, "Build": {
                    bat "mvn clean install"
                },
                failFast: true
            }

        }
        
        stage("Deploy") {
            steps {
                //bat "scp -r testEAR VM 2@192.168.80.11:C:/Users/VM 2/Documents/act-4/"

/*                 bat """
                "ssh VM 2@192.168.2.12 C:/Progam Files/IBM/WebSphere/AppServer/bin/wsadmin.sh" \
                -f C:/Users/VM 2/Documents/act-4/deploy.jython \
                -lang jython \
                -conntype SOAP \
                -host localhost \
                -user administrador \
                -password administrador
                """ */
            }
        }
    }
}