pipeline {
    agent any
    
    tools {
        maven "maven_tool"
        jdk "jdk8"
    }
    
    stages {
        stage("Checkout") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://gitlab.com/codilabs/Ear-Test.git']]])
            }
        }
        
        stage("Scan & Build") {
            environment {
                scannerHome = tool "sonar_scanner"
            }
            steps {
                bat "mvn clean install -DskipTests"
            }

        }
        
        stage("Deploy") {
            steps {
                bat "dir"
            }
        }
    }
}