pipeline {
    agent any
    
    tools {
        maven "maven_tool"
        jdk "jdk8"
    }
    
    stages {
        stage("Checkout") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://gitlab.com/codilabs/Ear-Test.git']]])
            }
        }
        
        stage("Scan & Build") {
            environment {
                scannerHome = tool "sonar_scanner"
            }
            steps {
                parallel "Scan": {
                    withSonarQubeEnv("sonarqube_server") {
                        bat """
                        "${scannerHome}/bin/sonar-scanner" \
                        -Dsonar.projectKey=earTest \
                        -Dsonar.projectName=Act-4-EarTest \
                        -Dsonar.projectVersion=0.1 \
                        -Dsonar.sources=testWAR/src \
                        -Dsonar.java.binaries=./target/
                        """
                    }
                }, "Build": {
                    bat "mvn clean install"
                },
                failFast: true
            }

        }
        
        stage("Deploy") {
            steps {
                bat "dir"
            }
        }
    }
}